package com.example.AtCapacity.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

/**
 * Represents a user in the system with authentication and role information.
 * Stored in MongoDB 'users' collection.
 */
@Document(collection = "users")
public class User {
    /** Unique identifier generated by MongoDB */
    @Id
    private String id;
    
    /** Username must be unique across all users */
    @Indexed(unique = true)
    private String username;
    
    /** Encrypted password using BCrypt */
    private String password;
    
    /** User's role for authorization (e.g., "USER", "ADMIN") */
    private String role;

    /** Default constructor required by MongoDB */
    public User() {}

    /**
     * Creates a new user with encrypted password.
     * @param username unique identifier for the user
     * @param password plain text password to be encrypted
     * @param role authorization role for the user
     */
    public User(String username, String password, String role) {
        this.username = username;
        this.password = new BCryptPasswordEncoder().encode(password);
        this.role = role;
    }

    // Getters and Setters
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    
    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }
    
    /**
     * Returns the encrypted password.
     * @return BCrypt encrypted password
     */
    public String getPassword() { return password; }

    /**
     * Encrypts and sets the password using BCrypt.
     * @param password plain text password to be encrypted
     */
    public void setPassword(String password) { 
        this.password = new BCryptPasswordEncoder().encode(password);
    }
    
    public String getRole() { return role; }
    public void setRole(String role) { this.role = role; }
}